the "remove all sketches" and "convert annotations to memory layer" b…
enricofer/redLayer pull request #16
Opened 2021-01-20 01:38 UTC by Fighterisr

fixed issues #12  and #15

2021-01-20 08:30 UTC, enricofer commented on redLayerModule.py
> +        self.removeAllAnnotations()
Why are you removing all annotations when using eraser tool? It should erase only the pointed annotation, linked to the erasing segment and pointed by sketch[3] see line 368

2021-01-20 08:30 UTC, enricofer commented on redLayerModule.py
>                      self.iface.mapCanvas().scene().removeItem( sketch[3] )
Anyway this line does not remove the pointed annotation. Could you investigate why?

2021-01-20 08:35 UTC, enricofer requested changes
Thanks for submission.
I gave a look to PR and I found issues related to erasing single annotation.
I fear that QgsAnnotation handling API break causes regressions even on saving and loading existing sketches with annotations.
Could you give a look and make some tests?

2021-01-20 10:26 UTC, Fighterisr commented
sadly i am very busy right now
i thought that the "erase all button" is supposed to delete everything, including annotations, so i included the call in removeSketchesAction()

the point of this commit was to fix the removeAllAnnotations() which did try to remove annotations from the scene but didn't work at all. mapCanvas().annotationItems() seems like the right way.

maybe in the future i'll try again

2021-01-20 10:26 UTC, closed without merging

2021-01-25 09:48 UTC, enricofer commented
I published a new plugin release 2.0.4 with all fixes for QgsAnnotation API break. Thanks for your submissions @Fighterisr @haubourg @SebastienPeillet :https://plugins.qgis.org/plugins/redLayer/

2021-01-26 09:33 UTC, haubourg commented
👍 Thanks @enricofer !